<script>
	function tecla(event){
		if(event.keyCode == 13){ 
			document.getElementById('loginform').submit()
		}
	}
</script>
<div class="container login-top">
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3 login-panel"></div>
		<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 login-panel">
			<div class="panel panel-info">
				<div class="panel-heading text-center">
				<strong>Iniciar Sesi&oacute;n</strong>
				</div>

				<div class="panel-body">
					<form class= "form-horizontal" id="loginform" name="loginform" action="" method="post">  
						<div class="grid_5 bare-form" >
							<?php if (isset($this->_error)): ?>
								<div id="_error" class="alert alert-error">
								<a class="close" data-dismiss="alert">x</a>
								<?php echo $this->_error; ?>
								</div>
							<?php endif; ?>   

							<input type="hidden" value="1" name="enviar" />
							<div  class= "form-group">
								<div  class= "col-sm-12" >
									<div class="input-group" align="center">
										<span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
										<input type="text" name="usuario" id="usuario" tabindex="2" placeholder="USUARIO" class="form-control" />
									</div>
								</div> 
							</div> 

							<div  class= "form-group" > 
								<div  class= "col-sm-12" > 
									<div class="input-group">
										<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
										<input type="password" name="pass" id="pass" tabindex="3" placeholder="CLAVE" class="form-control" onkeydown="javascript:tecla(event);"/>
									</div>
								</div> 
							</div>

							<div  class = "form-group " > 
								<div  class = "col-sm-12 text-center">
									<a  class="btn btn-primary" onclick="document.getElementById('loginform').submit()" style="cursor:pointer">
									<i class="glyphicon glyphicon-off"> Iniciar Sesi&oacute;n</i>
									</a>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>


