<?php if(isset($_SESSION["usuario"])):?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema - Tienda Virtual</title>
    <?php require_once 'inc/header.php'; ?>
    <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/bootstrap.min.css">
</head>
<body>
        <div class="new-count">
            <div class="clearfix"></div>
            <form class="form-horizontal col-xs-12" action="" method="POST" id="form" name="form1">
                <div class="acceso">
                    <input type="hidden" name="guardar" value="1" />
                    <?php if (isset($this->_error)): ?>
                        <div id="_error" class="alert alert-error">
                            <a class="close" data-dismiss="alert">x</a>
                            <?php echo $this->_error; ?>
                        </div>
                    <?php endif; ?>

                    <?php if (isset($this->_mensaje)): ?>
                        <div id="_mensaje" class="alert alert-success">
                            <a class="close" data-dismiss="alert">x</a>
                            <?php echo $this->_mensaje; ?>
                        </div>
                    <?php endif; ?>
                    <br>

                    <div class="form-group">
                        <label for="" class="control-label col-xs-3">Unidad Medida:</label>
                        <div class="col-xs-8">
                            <select class="form_imput" name="unidad" id="unidad" >
                                <option value="">-Seleccione-</option>
                                <?php foreach ($this->unidad as $unidad): ?>
                                        <option value="<?php echo $unidad->id; ?>" <?php if($this->datos->id_und_medida == $unidad->id){ ?> selected <?php } ?> ><?php echo $unidad->unidad_medida." (".$unidad->Simbolo.")"; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="" class="control-label col-xs-3">Producto:</label>
                        <div class="col-xs-8">
                            <input type="text" name="producto" id="producto" class="form-control" required placeholder="" value="<?php if (isset($this->datos->producto)) echo $this->datos->producto; ?>">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="" class="control-label col-xs-3">Precio:</label>
                        <div class="col-xs-8">
                            <input type="text" name="precio" id="precio" class="form-control" required
                                placeholder="" value="<?php if (isset($this->datos->precio)) echo $this->datos->precio; ?>">
                        </div>
                    </div>
                </div>

                <center>
                    <a href="#" class="btn btn-primary btn-center btn" onclick="document.getElementById('form').submit()">Guardar</a>
                </center>
            </form>
        </div>
    </div>
 
</body>
</html>
<?php 
else:
    header( 'Location: ../' );
endif;
?>