<?php if(isset($_SESSION["usuario"])):?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema - Tienda Virtual</title>
    <?php require_once 'inc/header.php'; ?>
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/jquery.fancybox.css" />
    <script src="<?php echo BASE_URL; ?>public/js/jquery.fancybox.js"></script>
</head>
<body>
    <?php require_once 'inc/menu-l.php'; ?>
    <script type="text/javascript">
        $("#productos").addClass("active");                  
    </script>
    <div class="container-fluid col-md-10 col-md-offset-2">
        <div class="row">
            <div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="space"></div>
                    <div>
                        <div class="contenido-button">
                            <a href="<?php echo BASE_URL; ?>productos/nuevo_producto"><span class="label label-primary">Añadir producto</span></a>

                            <a href="<?php echo BASE_URL; ?>productos"><span class="label label-primary">Actualizar</span>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div id="lista_registros">     
                        <?php if (isset($this->producto) && count($this->producto)) : ?>  
                            <table  class="table table-striped table-hover ">
                                <thead>
                                    <tr>
                                        <th class="text-center">PRODUCTO</th>
                                        <th class="text-center">UNIDAD</th>
                                        <th class="text-center">PRECIO</th>
                                        <th class="text-center">ACCIONES</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php foreach($this->producto as $producto):?>
                                    <tr class="info">
                                        <td><?php echo $producto->producto;?></td>
                                        <td><?php echo $producto->unidad_medida." (".$producto->Simbolo.")";?></td>
                                        <td><?php echo $producto->precio;?></td>
                                        <td>
                                            <a href="<?php echo BASE_URL; ?>productos/editar_producto/<?php echo $producto->id?>" class="ventanaproducto"><span class="label label-primary">Editar producto</span></a>

                                            <a href="javascript:borrar_producto(<?php echo $producto->id;?>)"><span class="label label-danger">Borrar producto</span></a>
                                        </td>
                                    </tr>
                                <?php endforeach;?>
                                <tr>
                                    <td colspan="4">
                                        <div class="clear"></div>
                                        <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        <?php else: ?>
                        <div class='alert alert-info'>
                        <strong>No hay Produtos creados.</strong>
                        </div>
                        <?php endif; ?>
                </div>
            </div>
        </div>
    </div>  
    <?php require_once 'inc/footer.php'; ?>
</body>
</html>
<?php 
else:
    header( 'Location: ../' );
endif;
?>