<?php if(isset($_SESSION["usuario"])):?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema - Tienda Virtual</title>
    <?php require_once 'inc/header.php'; ?>
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/jquery.fancybox.css" />
    <script src="<?php echo BASE_URL; ?>public/js/jquery.fancybox.js"></script>
    <script src="js/insumos.js" type="text/javascript"></script>
</head>
<body>
    <?php require_once 'inc/menu-l.php'; ?>
    <script type="text/javascript">
        $("#insumos").addClass("active");                  
    </script>
    <div class="container-fluid col-md-10 col-md-offset-2">
        <div class="row">
            <div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="space"></div>
                    <div>
                        <div class="contenido-button">
                            <a href="<?php echo BASE_URL; ?>insumos/nuevo_insumos"><span class="label label-primary">Añadir insumos</span></a>

                            <a href="<?php echo BASE_URL; ?>insumos"><span class="label label-primary">Actualizar</span>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div id="lista_registros">     
                        <?php if (isset($this->insumos) && count($this->insumos)) : ?>  
                            <table  class="table table-striped table-hover ">
                                <thead>
                                    <tr>
                                        <th class="text-center">CATEGORIA</th>
                                        <th class="text-center">INSUMO</th>
                                        <th class="text-center">ACCIONES</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php foreach($this->insumos as $insumos):?>
                                    <tr class="info">
                                        <td><?php echo $insumos->categoria;?></td>
                                        <td><?php echo $insumos->insumo;?></td>
                                        <td><?php echo $insumos->precio;?></td>
                                        <td>
                                            <a href="<?php echo BASE_URL; ?>insumos/editar_insumos/<?php echo $insumos->id?>" class="ventanainsumos"><span class="label label-primary">Editar insumos</span></a>

                                            <a href="javascript:borrar_insumos(<?php echo $insumos->id;?>)"><span class="label label-danger">Borrar insumos</span></a>
                                        </td>
                                    </tr>
                                <?php endforeach;?>
                                <tr>
                                    <td colspan="4">
                                        <div class="clear"></div>
                                        <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        <?php else: ?>
                        <div class='alert alert-info'>
                        <strong>No hay insumos  creados.</strong>
                        </div>
                        <?php endif; ?>


                        



                </div>
            </div>
        </div>
    </div>  
    <?php require_once 'inc/footer.php'; ?>
</body>
</html>
<?php 
else:
    header( 'Location: ../' );
endif;
?>