<?php if (isset($this->proveedores) && count($this->proveedores)) : ?>  
                            <table class='table table-striped table-hover'>
                                <thead>
                                    
                                    <tr>
                                        <th class="text-center">TIPO PROVEEDOR</th>
                                        <th class="text-center">TIPO DOCUMENTO</th>
                                        <th class="text-center">NUMERO DOCUMENTO</th>
                                        <th class="text-center">NOMBRE</th>
                                        <th class="text-center">DIRECCION</th>
                                        <th class="text-center">CONTACTO</th>
                                        <th class="text-center">EMAIL</th>
                                        <th class="text-center">TELEFONO</th>
                                        <th class="text-center">ACCIONES</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php foreach($this->proveedores as $proveedores):?>
                                    <tr class="info">
                                        <td>
                                            <?php if($proveedores->tipo_proveedor == 1){ echo "Combustibles"; }
                                            else if($proveedores->tipo_proveedor == 2){ echo "Materiales"; }
                                            else if($proveedores->tipo_proveedor == 3){ echo "Servicios"; }?>
                                        </td>

                                        <td><?php echo $proveedores->tdoc;?></td>
                                        <td><?php echo $proveedores->nit;?></td>
                                        <td><?php echo $proveedores->razon_social;?></td>
                                        <td><?php echo $proveedores->direccion;?></td>
                                        <td><?php echo $proveedores->contacto;?></td>
                                        <td><?php echo $proveedores->email_contacto;?></td>
                                        <td><?php echo $proveedores->numero_contacto;?></td>
                                        <td>
                                            <a href="<?php echo BASE_URL; ?>proveedoress/editar_proveedor/<?php echo $proveedores->id?>" class=" ventanaproveedores"><span class="glyphicon glyphicon-cog"></span></a>

                                            <a href="javascript:borrar_proveedor(<?php echo $proveedores->id;?>)" class=""><span class="glyphicon glyphicon-trash"></span></a>
                                        </td>
                                </tr>
                                <?php endforeach;?>
                                <tr class="default">
                                    <td colspan="8">
                                        <div class="clear"></div>
                                        <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        <?php else: ?>
                        <div class='alert alert-dismissible alert-danger'>
                            <strong>No hay proveedores creados.</strong>
                        </div>
                        <?php endif; ?>