<?php if(isset($_SESSION["usuario"])):?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema - Tienda Virtual</title>
    <?php require_once 'inc/header.php'; ?>
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/jquery.fancybox.css" />
    <script src="<?php echo BASE_URL; ?>public/js/jquery.fancybox.js"></script>    
</head>
<body>
    <?php require_once 'inc/menu-l.php'; ?>
    <script type="text/javascript">
        $("#compras").addClass("active");                  
    </script>
    <div class="container-fluid col-md-10 col-md-offset-2">
        <div class="row">
            <div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="space"></div>
                    <div>
                        <div class="contenido-button">
                            <a href="<?php echo BASE_URL; ?>compras/nueva_compra"><span class="label label-primary">Nueva Compra</span></a>

                            <a href="<?php echo BASE_URL; ?>compras"><span class="label label-primary">Actualizar lista</span>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div id="lista_registros">     
                        <?php if (isset($this->encabezado) && count($this->encabezado)) : ?>  
                            <table class="table table-striped table-hover ">
                                <thead>
                                    <tr>
                                        <th class="text-center">N°</th>
                                        <th class="text-center">FECHA</th>
                                        <th class="text-center">PROVEEDOR</th>
                                        <th class="text-center">ESTADO</th>
                                        <th class="text-center">TOTAL</th>
                                        <th class="text-center">ACCIONES</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php foreach($this->encabezado as $encabezado):?>
                                    <tr>
                                        <td><?php echo $encabezado->prefijo." 000".$encabezado->num_prefijo;?></td>
                                        <td><?php echo $encabezado->fecha_compra;?></td>
                                        <td><?php echo $encabezado->razon_social;?></td>
                                        <td class="text-center"><?php if ($encabezado->estado_compra == 1){ echo "Creado";} elseif ($encabezado->estado_compra == 2){echo "Finalizado";}?></td>
                                        <td>$<?php echo $encabezado->total_compra;?></td>
                                        
                                    <td class="text-center">

                                        <?php if ($encabezado->estado_compra == 1){?>

                                        <a data-toggle="tooltip" data-placement="left" title="lista detalles" href="<?php echo BASE_URL; ?>compras/detalle/<?php echo $encabezado->id?>"><span class="glyphicon glyphicon-list"></span></a>
                                        &nbsp;

                                        <a data-toggle="tooltip" data-placement="left" title="cambiar estado" href="javascript:cambiar_estado(<?php echo $encabezado->id;?>)"><span class="glyphicon glyphicon-repeat"></span></a>

                                        &nbsp;
                                        <?php } ?>

<!--
                                        <a data-toggle="tooltip" data-placement="left" title="Ver factura" href="<?php echo BASE_URL; ?>compras/ver_documento/<?php echo $encabezado->id?>"><span class="glyphicon glyphicon-modal-window"></span></a>-->
                                        
                                    </td>
                                </tr>
                                <?php endforeach;?>
                                <tr>
                                    <td colspan="7">
                                        <div class="clear"></div>
                                        <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        <?php else: ?>
                        <div class="space"></div>
                        <div class='alert alert-info'>
                        <strong>No hay compras creadas.</strong>
                        </div>
                        <?php endif; ?>
                </div>
            </div>
        </div>
    </div>  
    <?php require_once 'inc/footer.php'; ?>
    <script type="text/javascript">
        $(function () {
          $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
</body>
</html>
<?php 
else:
    header( 'Location: ../' );
endif;
?>