<?php if (isset($this->encabezado) && count($this->encabezado)) : ?>  
                            <table class="table table-striped table-hover ">
                                <thead>
                                    <tr>
                                        <th class="text-center">N°</th>
                                        <th class="text-center">FECHA</th>
                                        <th class="text-center">PROVEEDOR</th>
                                        <th class="text-center">ESTADO</th>
                                        <th class="text-center">TOTAL</th>
                                        <th class="text-center">ACCIONES</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php foreach($this->encabezado as $encabezado):?>
                                    <tr>
                                        <td><?php echo $encabezado->prefijo." 000".$encabezado->num_prefijo;?></td>
                                        <td><?php echo $encabezado->fecha_venta;?></td>
                                        <td><?php echo $encabezado->nomcom;?></td>
                                        <td class="text-center"><?php if ($encabezado->estado_venta == 1){ echo "Creado";} elseif ($encabezado->estado_venta == 2){ echo "Pendiente";} elseif ($encabezado->estado_venta == 3){echo "Pendiente Factura";} elseif ($encabezado->estado_venta == 4){echo "Finalizado";}?></td>
                                        <td>$<?php echo $encabezado->total_venta;?></td>
                                        
                                    <td class="text-center">

                                        <?php if ($encabezado->estado_venta == 1){?>

                                        <a data-toggle="tooltip" data-placement="left" title="lista detalles" href="<?php echo BASE_URL; ?>ventas/detalle/<?php echo $encabezado->id?>"><span class="glyphicon glyphicon-list"></span></a>
                                        &nbsp;

                                        <a data-toggle="tooltip" data-placement="left" title="cambiar estado" href="javascript:cambiar_estado(<?php echo $encabezado->id;?>)"><span class="glyphicon glyphicon-repeat"></span></a>

                                        &nbsp;
                                        <?php } ?>


                                        <a data-toggle="tooltip" data-placement="left" title="Ver factura" href="<?php echo BASE_URL; ?>ventas/ver_factura/<?php echo $encabezado->id?>"><span class="glyphicon glyphicon-modal-window"></span></a>
                                        
                                    </td>
                                </tr>
                                <?php endforeach;?>
                                <tr>
                                    <td colspan="7">
                                        <div class="clear"></div>
                                        <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        <?php else: ?>
                        <div class="space"></div>
                        <div class='alert alert-info'>
                        <strong>No hay compras creadas.</strong>
                        </div>
                        <?php endif; ?>