<?php if (isset($this->usuario) && count($this->usuario)) : ?>  
    <table class='table  table-bordered table-hover table-condensed'>
        <thead class="alert alert-info text-head">
            <tr>
                <th class="text-center">N°</th>
                <th class="text-center">USUARIO</th>
                <th class="text-center">ESTADO</th>
                <th class="text-center">ACCIONES</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($this->usuario as $usuario):?>
            <tr>
                <td><?php echo $usuario->id;?></td>
                <td><?php echo $usuario->usuario;?></td>
                <td><?php if($usuario->estado == 1){echo "Activo";}else{echo "inactivo";}?> 
                </td>
            <td>
                <a href="<?php echo BASE_URL; ?>usuarios/editar_usuario/<?php echo $usuario->id?>" class="btn2 ventanausuario"><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/> </a>
                <a href="<?php echo BASE_URL; ?>usuarios/cambio_clave/<?php echo $usuario->id?>" class="btn2 ventanausuario"><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/> </a>

                <a href="javascript:borrar_usuario(<?php echo $usuario->id;?>)" class="btn2"><img src="<?php echo BASE_URL; ?>public/img/remover_todos.png" style="vertical-align:middle"/></a>
            </td>
        </tr>
        <?php endforeach;?>
        <tr>
            <td colspan="4">
                <div class="clear"></div>
                <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
            </td>
        </tr>
        </tbody>
    </table>
<?php else: ?>
    <div class='alert alert-info'>
    <strong>No hay usuarios creados.</strong>
    </div>
<?php endif; ?>