<?php if(isset($_SESSION["usuario"])):?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema - Tienda Virtual</title>
    <?php require_once 'inc/header.php'; ?>
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/jquery.fancybox.css" />
    <script src="<?php echo BASE_URL; ?>public/js/jquery.fancybox.js"></script>
</head>
<body>
    <?php require_once 'inc/menu-l.php'; ?>
    <script type="text/javascript">
        $("#ventas").addClass("active");                  
    </script>
    <div class="container-fluid col-md-10 col-md-offset-2">
        <div class="row">
            <div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="space"></div>
                    <div>
                        <div class="contenido-button">
                            <?php if($this->datos->total_venta > $this->tabono){ ?>
                            <a href="<?php echo BASE_URL; ?>ventas/agregar_abono/<?php echo $this->idenc;?>"><span class="label label-primary">Agregar abono venta</span></a>
                            <?php } ?>

                            <a href="<?php echo BASE_URL; ?>ventas/abonos/<?php echo $this->idenc;?>"><span class="label label-primary">Actualizar lista</span>
                            </a>

                            <a href="<?php echo BASE_URL; ?>ventas"><span class="label label-primary">Regresar a ventas</span>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div id="lista_registros">

                        <div class='alert alert-info'>
                        <strong>Total del venta $<?php echo $this->datos->total_venta;?>.
                        <?php if (isset($this->tabono)){?>
                            Total Pendiente de pago $<?php echo $this->datos->total_venta - $this->tabono;?></strong>
                        <?php }else{?>
                            Total Pendiente de pago $<?php echo $this->datos->total_venta;?></strong>
                        <?php } ?>
                        </div>    
                        <?php if (isset($this->abono) && count($this->abono)) : ?>  
                            <table class="table table-striped table-hover ">
                                <thead>
                                    <tr>
                                        <th class="text-center">FECHA ABONO</th>
                                        <th class="text-center">VALOR</th>
                                        <th class="text-center">ACCIONES</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php foreach($this->abono as $abono):?>
                                    <tr>
                                        <td><?php echo date('d-m-Y', strtotime($abono->fecha_abono));?></td>
                                        <td>$<?php echo $abono->valor;?></td>                                        
                                    <td>
                                        <?php if($this->datos->total_venta > $this->tabono){ ?>
                                            <a href="<?php echo BASE_URL; ?>ventas/editar_abono/<?php echo $abono->id?>" class="ventanaabono"><span class="label label-primary">editar abono</span></a>

                                            <a href="javascript:borrar_abono(<?php echo $abono->id;?>)"><span class="label label-danger">Borrar abono</span></a>
                                        <?php } ?>
                                    </td>
                                </tr>
                                <?php endforeach;?>
                                <tr>
                                    <td colspan="6">
                                        <div class="clear"></div>
                                        <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        <?php else: ?>
                        <div class="space"></div>
                        <div class='alert alert-info'>
                        <strong>No hay detalles de venta creados.</strong>
                        </div>
                        <?php endif; ?>
                </div>
            </div>
        </div>
    </div>  
    <?php require_once 'inc/footer.php'; ?>
</body>
</html>
<?php 
else:
    header( 'Location: ../' );
endif;
?>