<?php if(isset($_SESSION["usuario"])):?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema - Tienda Virtual</title>
    <?php require_once 'inc/header.php'; ?>
    <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/custom-theme/jquery-ui-1.10.3.custom.css"> 
</head>
<body>
    <?php require_once 'inc/menu-l.php'; ?>
    <script type="text/javascript">
        $("#ventas").addClass("active");                  
    </script>
    <div class="container-fluid col-md-10 col-md-offset-2">
        <div class="row">
            <div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="space"></div>
                    <div class="navbar navbar-default">
                            <a href="<?php echo BASE_URL; ?>ventas/abonos/<?php echo $this->idenc;?>" 
                                class="link-actualizar pull-right"><i class='glyphicon glyphicon-arrow-left'></i> Volver
                            </a>
                        </div>
                    </div>

                    <div class="new-count">
                        <div class="clearfix"></div>
                        <form class="form-horizontal" action="" method="POST" id="form" name="form1">
                            <div class="acceso">
                                <input type="hidden" name="guardar" value="1" />
                                <?php if (isset($this->_error)): ?>
                                    <div id="_error" class="alert alert-error">
                                        <a class="close" data-dismiss="alert">x</a>
                                        <?php echo $this->_error; ?>
                                    </div>
                                <?php endif; ?>

                                <?php if (isset($this->_mensaje)): ?>
                                    <div id="_mensaje" class="alert alert-success">
                                        <a class="close" data-dismiss="alert">x</a>
                                        <?php echo $this->_mensaje; ?>
                                    </div>
                                <?php endif; ?>
                                <br>

                                <div class="form-group">
                                    <label for="" class="control-label col-xs-3">Valor Abono:</label>
                                    <div class="col-xs-8">
                                        <input type="text" name="valor" id="valor" class="form-control" required placeholder="<?php echo $this->sugerido;?>" value="">
                                    </div>
                                </div>

                            </div>

                            <center>
                                <a href="#" class="btn btn-primary btn-center btn" onclick="document.getElementById('form').submit()">Guardar</a>
                            </center>
                        </form>
                    </div>
                </div>
 
</body>
</html>
<?php 
else:
    header( 'Location: ../' );
endif;
?>