<html>
<head>
	<meta charset="UTF-8">
	<title>Certificado</title>
	<link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/cssorigen/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/cssorigen/flexboxgrid.min.css">
	<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/cssorigen/certificado.css">
	<link href='https://fonts.googleapis.com/css?family=Roboto:400,700italic' rel='stylesheet' type='text/css'>
</head>
<body>
	<header class="contenedor">
		<div class="col-xs-6">
			<img class="logomine" src="<?php echo BASE_URL; ?>public/img/mineria.jpg">

		</div>
		<div class="col-xs-6 text-right"><h2>CERTIFICADO DE ORIGEN</h2></div>
	</header>
	<section class="contenedor">

		<table class="table table-bordered ">
			  <thead >
				  <tr>
				    <th class="col-xs">Expedientes</th>

				    <th class="col-xs">Nombre Comercial
										
				    </th>

				    <th class="col-xs">Minerales</th>
				    <th class="col-xs">Ubicaciones</th>

				    
				  </tr>
			  </thead>
			  <tbody>
				  <tr>
				    <td class="col-xs text-center"><input type="text" name="expediente"></td>
				    <td class="col-xs"><input type="text" name="nombre" value="Playa Rica"></td>
				    <td class="col-xs"><input type="text" name="minerales"></td>
				    <td class="col-xs"><input type="text" name="ubicaciones" value="Roldanillo valle del cauca"></td>
				  </tr>
			  </tbody>
			</table>
	</section>
	<section class="contenedor">
		<p class="text-center col-xs-10">ARENERA EL PASO - TIERRA BLANCA</p>
		<p class="text-right folio col-xs-2">  <?php  echo  "000" .  $this->datos->num_co;  ?></p>
	</section>
	<section class="contenedor datos">
		<div class="bolqueta col-xs-12 flex">
			<p class="col-xs-2">Bolqueta Placa</p>
			<input class="col-xs-10" type="text" name="bolqueta_placa" value="<?php echo $this->vehiculo->placa;?>">
		</div>
		<div class="col-xs-12 flex">
			<p class="col-xs-1">Cliente</p>
			<input class="col-xs-11" type="text" name="cliente" value="<?php echo $this->cliente->nomcom;?>">
		</div>
		<div class="col-xs-12 flex">
			<p class="col-xs-1">Destino</p>
			<input class="col-xs-11" type="text" name="destino" value="<?php echo $this->cliente->departamento." - ".$this->cliente->ciudad;?>">
		</div>
		<div class="col-xs-4 flex">
			<p class="col-xs-2">FECHA</p>
			<input class="col-xs-10" type="text" name="fecha" value="<?php echo date('d-m-Y', strtotime($this->datos->fecha_venta));?>">
		</div>
		<!--<div class="col-xs-8 flex">
			<p class="col-xs-3">Hora de despacho:</p>
			<input class="col-xs-9" type="text" name="hora_despacho">
		</div>-->
	</section>
	<section class="contenedor material">
		
		<div class="col-xs-3">
			<p>MATERIAL:</p>
		</div>
		<div class="col-xs-5 flex">
			<p>Arena gruesa</p>
			<input type="checkbox" name="arena_gruesa">
		</div>
		<div class="col-xs-4 flex">
			<p>Balastro</p>
			<input type="checkbox"  name="balastro">
		</div>
	</section>
	<section class="contenedor">
		<p class="text-center">Telefónos: 313 627 76 05 - 312 295 60 27 - 317 621 41 60</p>
	</section>
	<section class="contenedor firma">
		<div class="flex">
			<p class="col-xs-3">Firma del Despachador</p>
			<input type="textbox" name="firma_despachador" />
		</div>
	</section>
	<footer class="contenedor">
		<p>- Este certificado sólo es válido por el viaje anteriormente descrito</p>
		<p>- Vigente para la fecha de su expedición</p>
		<p>- Favor verificar autenticidad del certificado en los números telefónico relacionados.</p>
	</footer>
</body>
</html>

