<?php if(isset($_SESSION["usuario"])):?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema - Tienda Virtual</title>
    <?php require_once 'inc/header.php'; ?>
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/jquery.fancybox.css" />
    <script src="<?php echo BASE_URL; ?>public/js/jquery.fancybox.js"></script>
</head>
<body>
    <?php require_once 'inc/menu-l.php'; ?>
    <script type="text/javascript">
        $("#ventas").addClass("active");                  
    </script>
    <div class="container-fluid col-md-10 col-md-offset-2">
        <div class="row">
            <div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="space"></div>
                    <div>
                        <div class="contenido-button">
                            <a href="<?php echo BASE_URL; ?>ventas/agregar_detalle/<?php echo $this->idenc;?>"><span class="label label-primary">agregar detalle venta</span></a>

                            <a href="<?php echo BASE_URL; ?>ventas/detalle/<?php echo $this->idenc;?>"><span class="label label-primary">Actualizar lista</span>
                            </a>

                            <a href="<?php echo BASE_URL; ?>ventas"><span class="label label-primary">ventas</span>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div id="lista_registros">     
                        <?php if (isset($this->detalle) && count($this->detalle)) : ?>  
                            <table class="table table-striped table-hover ">
                                <thead>
                                    <tr>
                                        <th class="text-center">PRODUCTO</th>
                                        <th class="text-center">VR UNITARIO</th>
                                        <th class="text-center">CANTIDAD</th>
                                        <th class="text-center">DESCUENTO</th>
                                        <th class="text-center">TOTAL</th>
                                        <th class="text-center">ACCIONES</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php foreach($this->detalle as $detalle):?>
                                    <tr>
                                        <td><?php echo $detalle->producto;?></td>
                                        <td>$<?php echo $detalle->precio;?></td>
                                        <td><?php echo $detalle->cantidad;?></td>
                                        <td>$<?php echo $detalle->descuento;?></td>
                                        <td>$<?php echo $detalle->total_detalle;?></td>
                                        
                                    <td>

                                        <?php if($detalle->id_remision==0){?>
                                            <a href="<?php echo BASE_URL; ?>ventas/editar_detalle/<?php echo $detalle->id?>" class="ventanadetalle"><span class="label label-primary">editar detalle</span></a>

                                            <a href="javascript:borrar_detalle(<?php echo $detalle->id;?>)"><span class="label label-danger">Borrar detalle</span></a>
                                        <?php } ?>
                                    </td>
                                </tr>
                                <?php endforeach;?>
                                <tr>
                                    <td colspan="4">
                                        <div class="clear"></div>
                                        <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        <?php else: ?>
                        <div class="space"></div>
                        <div class='alert alert-info'>
                        <strong>No hay detalles de venta creados.</strong>
                        </div>
                        <?php endif; ?>
                </div>
            </div>
        </div>
    </div>  
    <?php require_once 'inc/footer.php'; ?>
</body>
</html>
<?php 
else:
    header( 'Location: ../' );
endif;
?>