<?php if(isset($_SESSION["usuario"])):?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema - Tienda Virtual</title>
    <?php require_once 'inc/header.php'; ?>
    <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/bootstrap.min.css">
</head>
<body>
        <div class="new-count">
            <div class="clearfix"></div>
            <form class="form-horizontal col-xs-12" action="" method="POST" id="form" name="form1">
                <div class="acceso">
                    <input type="hidden" name="guardar" value="1" />
                    <?php if (isset($this->_error)): ?>
                        <div id="_error" class="alert alert-error">
                            <a class="close" data-dismiss="alert">x</a>
                            <?php echo $this->_error; ?>
                        </div>
                    <?php endif; ?>

                    <?php if (isset($this->_mensaje)): ?>
                        <div id="_mensaje" class="alert alert-success">
                            <a class="close" data-dismiss="alert">x</a>
                            <?php echo $this->_mensaje; ?>
                        </div>
                    <?php endif; ?>
                    <br>

                    <div class="form-group">
                        <label for="" class="control-label col-xs-3">Cliente:</label>
                        <div class="col-xs-8">
                            <select class="form_imput" name="id_cliente" id="id_cliente" >
                                <option value="">-Seleccione-</option>
                                <?php foreach ($this->cliente as $cliente): ?>
                                        <option value="<?php echo $cliente->id; ?>" <?php if($this->datos->id_cliente == $cliente->id){ ?> selected <?php } ?>><?php echo $cliente->nomcom; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>

                    

                    <div class="form-group">
                        <label for="" class="control-label col-xs-3">Cliente:</label>
                        <div class="col-xs-8">
                            <select class="form_imput" name="id_empleado" id="id_empleado" >
                                <option value="">-Seleccione-</option>
                                <?php foreach ($this->empleado as $empleado): ?>
                                        <option value="<?php echo $empleado->id; ?>" <?php if($this->datos->id_empleado == $empleado->id){ ?> selected <?php } ?>><?php echo $empleado->nombres." ".$empleado->apellidos; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>


                    <div class="form-group">
                        <label for="" class="control-label col-xs-3">Placa:</label>
                        <div class="col-xs-8">
                            <select class="form_imput" name="id_placa" id="id_placa" >
                                <option value="">-Seleccione-</option>
                                <?php foreach ($this->placa as $placa): ?>
                                    <option value="<?php echo $placa->id; ?>" <?php if (isset($this->datos->id_placa) and ($this->datos->id_placa == $placa->id)): ?> selected='selected' <?php endif; ?>><?php echo $placa->placa; ?></option>
        
                            <?php endforeach; ?>
                            </select>
                        </div>
                    </div>

                </div>

                <center>
                    <a href="#" class="btn btn-primary btn-center btn" onclick="document.getElementById('form').submit()">Guardar</a>
                </center>
            </form>
        </div>
    </div>
 
</body>
</html>
<?php 
else:
    header( 'Location: ../' );
endif;
?>