<?php if(isset($_SESSION["usuario"])):?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema - Tienda Virtual</title>
    <?php require_once 'inc/header.php'; ?>
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/jquery.fancybox.css" />
    <script src="<?php echo BASE_URL; ?>public/js/jquery.fancybox.js"></script>    <script src="ventas.js"></script> 
</head>
<body>
    <?php require_once 'inc/menu-l.php'; ?>
    <script type="text/javascript">
        $("#ventas").addClass("active");                  
    </script>
    <div class="container-fluid col-md-10 col-md-offset-2">
        <div class="row">
            <div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="space"></div>
                    <div>
                        <div class="contenido-button">

                            <a href="<?php echo BASE_URL; ?>ventas"><span class="label label-primary">Actualizar lista</span>
                            </a>

                            <a href="<?php echo BASE_URL; ?>ventas"><span class="label label-primary">ventas</span>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div id="lista_registros">     
                        <?php if (isset($this->pendientes) && count($this->pendientes)) : ?>  
                            <table class="table table-striped table-hover ">
                                <thead>
                                    <tr>
                                        <th class="text-center">N°</th>
                                        <th class="text-center">FECHA</th>
                                        <th class="text-center">FORMA PAGO</th>
                                        <th class="text-center">ESTADO</th>
                                        <th class="text-center">TOTAL</th>
                                        <th class="text-center">ACCIONES</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php foreach($this->pendientes as $pendientes):?>
                                    <tr>
                                        <td><?php echo $pendientes->prefijo." 000".$pendientes->num_prefijo;?></td>
                                        <td><?php echo $pendientes->fecha_venta;?></td>
                                        <td class="text-center"><?php if ($pendientes->forma_pago == 1){ echo "Efectivo";} elseif ($pendientes->forma_pago == 2){ echo "Remision";} elseif ($pendientes->forma_pago == 3){ echo "InfoRem";}?></td>
                                        <td class="text-center"><?php if ($pendientes->estado_venta == 1){ echo "Creado";} elseif ($pendientes->estado_venta == 2){ echo "Pendiente";} elseif ($pendientes->estado_venta == 3){echo "Pendiente Factura";} elseif ($pendientes->estado_venta == 4){echo "Finalizado";}?></td>
                                        <td>$<?php echo $pendientes->total_venta;?></td>
                                        
                                    <td>
                                        <!--<a data-toggle="tooltip" data-placement="left" title="Editar venta" href="<?php echo BASE_URL; ?>ventas/editar_venta/<?php echo $encabezado->id?>" class="ventanaventa"><span class="glyphicon glyphicon-cog"></span></a>

                                        <a data-toggle="tooltip" data-placement="left" title="Eliminar venta" href="javascript:borrar_venta(<?php echo $encabezado->id;?>)"><span class="glyphicon glyphicon-trash"></span></a>-->

                                        <a data-toggle="tooltip" data-placement="left" title="facturar" href="javascript:facturar(<?php echo $pendientes->id;?>)"><span class="glyphicon glyphicon-repeat"></span></a>
                                        &nbsp;
                                        
                                    </td>
                                </tr>
                                <?php endforeach;?>
                                <tr>
                                    <td colspan="7">
                                        <div class="clear"></div>
                                        <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        <?php else: ?>
                        <div class="space"></div>
                        <div class='alert alert-info'>
                        <strong>No hay pendientes por facturas.</strong>
                        </div>
                        <?php endif; ?>
                </div>
            </div>
        </div>
    </div>  
    <?php require_once 'inc/footer.php'; ?>
    <script type="text/javascript">
        $(function () {
          $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
</body>
</html>
<?php 
else:
    header( 'Location: ../' );
endif;
?>