<?php if(isset($_SESSION["usuario"])):?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema - Tienda Virtual</title>
    <?php require_once 'inc/header.php'; ?>
    <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/custom-theme/jquery-ui-1.10.3.custom.css"> 
</head>
<body>
    <?php require_once 'inc/menu-l.php'; ?>
    <script type="text/javascript">
        $("#ventas").addClass("active");                  
    </script>
    <div class="container-fluid col-md-10 col-md-offset-2">
        <div class="row">
            <div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="space"></div>
                    <div class="navbar navbar-default">
                            <a href="<?php echo BASE_URL; ?>ventas" 
                                class="link-actualizar pull-right"><i class='glyphicon glyphicon-arrow-left'></i> Volver
                            </a>
                        </div>
                    </div>

                    <div class="new-count">
                        <div class="clearfix"></div>
                        <form class="form-horizontal" action="" method="POST" id="form" name="form1">
                            <div class="acceso">
                                <input type="hidden" name="guardar" value="1" />
                                <?php if (isset($this->_error)): ?>
                                    <div id="_error" class="alert alert-error">
                                        <a class="close" data-dismiss="alert">x</a>
                                        <?php echo $this->_error; ?>
                                    </div>
                                <?php endif; ?>

                                <?php if (isset($this->_mensaje)): ?>
                                    <div id="_mensaje" class="alert alert-success">
                                        <a class="close" data-dismiss="alert">x</a>
                                        <?php echo $this->_mensaje; ?>
                                    </div>
                                <?php endif; ?>
                                <br>

                                <div class="form-group">
                                    <label for="" class="control-label col-xs-3">Cliente:</label>
                                    <div class="col-xs-8">
                                        <select class="form-control form_imput" name="id_cliente" id="id_cliente" >
                                            <option value="">-Seleccione-</option>
                                            <?php foreach ($this->cliente as $cliente): ?>
                                                    <option value="<?php echo $cliente->id; ?>"><?php echo $cliente->nomcom; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="" class="control-label col-xs-3">Empleado:</label>
                                    <div class="col-xs-8">
                                        <select class="form-control form_imput" name="id_empleado" id="id_empleado" >
                                            <option value="">-Seleccione-</option>
                                            <?php foreach ($this->empleado as $empleado): ?>
                                                    <option value="<?php echo $empleado->id; ?>"><?php echo $empleado->nombres." ".$empleado->apellidos; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="" class="control-label col-xs-3">Despachador:</label>
                                    <div class="col-xs-8">
                                        <select class="form-control form_imput" name="id_despachador" id="id_despachador" >
                                            <option value="">-Seleccione-</option>
                                            <?php foreach ($this->despachador as $despachador): ?>
                                                    <option value="<?php echo $despachador->id; ?>"><?php echo $despachador->nombres." ".$despachador->apellidos; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="" class="control-label col-xs-3">Placa:</label>
                                    <div class="col-xs-8">
                                        <select class="form-control form_imput" name="id_placa" id="id_placa" >
                                            <option value="">-Seleccione-</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="" class="control-label col-xs-3">Forma Pago:</label>
                                    <div class="col-xs-8">
                                        <select class="form-control form_imput" name="forma" id="forma" >
                                            <option value="">-Seleccione-</option>
                                            <option value="1">-Efectivo-</option>
                                            <option value="2">-Remision-</option>
                                            <option value="3">-InfoRem-</option>
                                            <option value="4">-Factura Inforem-</option>
                                        </select>
                                    </div>
                                </div>

                            </div>

                            <center>
                                <a href="#" class="btn btn-primary btn-center" onclick="document.getElementById('form').submit()">Guardar</a>
                            </center>
                        </form>
                    </div>
                </div>
 
</body>
</html>
<?php 
else:
    header( 'Location: ../' );
endif;
?>