<?php if(isset($_SESSION["usuario"])):?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema - Tienda Virtual</title>
    <?php require_once 'inc/header.php'; ?>
</head>
<body>
        <div class="new-count">
            <div class="clearfix"></div>
            <form class="form-horizontal" action="" method="POST" id="form" name="form1">
                <div class="acceso">
                    <input type="hidden" name="guardar" value="1" />
                    <?php if (isset($this->_error)): ?>
                        <div id="_error" class="alert alert-error">
                            <a class="close" data-dismiss="alert">x</a>
                            <?php echo $this->_error; ?>
                        </div>
                    <?php endif; ?>

                    <?php if (isset($this->_mensaje)): ?>
                        <div id="_mensaje" class="alert alert-success">
                            <a class="close" data-dismiss="alert">x</a>
                            <?php echo $this->_mensaje; ?>
                        </div>
                    <?php endif; ?>
                    <br>

                    <div class="form-group">
                        <label for="" class="control-label col-xs-3">Cliente:</label>
                        <div class="col-xs-8">
                            <select class="form_imput" name="id_cliente" id="id_cliente" >
                                <option value="">-Seleccione-</option>
                                <?php foreach ($this->cliente as $cliente): ?>
                                        <option value="<?php echo $cliente->id; ?>" <?php if($this->datos->id_cliente == $cliente->id){ ?> selected <?php } ?>><?php echo $cliente->nomcom; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="" class="control-label col-xs-3">Placa:</label>
                        <div class="col-xs-8">
                            <input type="text" name="placa" id="placa" class="form-control" required placeholder="ZZZ000" 
                            value="<?php if (isset($this->datos->placa)) echo strtoupper($this->datos->placa); ?>">
                        </div>
                    </div>

                </div>

                <center>
                    <a href="#" class="btn btn-primary btn-center btn" onclick="document.getElementById('form').submit()">Guardar</a>
                </center>
            </form>
        </div>
    </div>
 
</body>
</html>
<?php 
else:
    header( 'Location: ../' );
endif;
?>