<?php if(isset($_SESSION["usuario"])):?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema - Tienda Virtual</title>
    <?php require_once 'inc/header.php'; ?>
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/jquery.fancybox.css" />
    <script src="<?php echo BASE_URL; ?>public/js/jquery.fancybox.js"></script>
</head>
<body>
    <?php require_once 'inc/menu-l.php'; ?>
    <script type="text/javascript">
        $("#vehiculos").addClass("active");                  
    </script>
    <div class="container-fluid col-md-10 col-md-offset-2">
        <div class="row">
            <div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="space"></div>
                    <div>
                        <div class="contenido-button">
                            <a href="<?php echo BASE_URL; ?>vehiculos/nuevo_vehiculo"><span class="label label-primary">Nueva vehículo</span></a>

                            <a href="<?php echo BASE_URL; ?>vehiculos"><span class="label label-primary">Actualizar lista<span>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div id="lista_registros">     
                        <?php if (isset($this->vehiculo) && count($this->vehiculo)) : ?>  
                            <table  class="table table-striped table-hover ">
                                <thead>
                                    <tr>
                                        <th class="text-center">CLIENTE</th>
                                        <th class="text-center">PLACA</th>
                                        <th class="text-center">ACCIONES</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php foreach($this->vehiculo as $vehiculo):?>
                                    <tr>
                                        <td><?php echo $vehiculo->nomcom;?></td>
                                        <td><?php echo strtoupper($vehiculo->placa);?></td>
                                    <td>
                                        <a href="<?php echo BASE_URL; ?>vehiculos/editar_vehiculo/<?php echo $vehiculo->id?>" class="ventanavehiculo"><span class="label label-primary">Editar vehículo</span></a>

                                        <a href="javascript:borrar_vehiculo(<?php echo $vehiculo->id;?>)"><span class="label label-danger">Borrar vehículo</span></a>
                                    </td>
                                </tr>
                                <?php endforeach;?>
                                <tr>
                                    <td colspan="4">
                                        <div class="clear"></div>
                                        <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        <?php else: ?>
                        <div class="space"></div>
                        <div class='alert alert-info'>
                        <strong>No hay vehiculos creados.</strong>
                        </div>
                        <?php endif; ?>
                </div>
            </div>
        </div>
    </div>  
    <?php require_once 'inc/footer.php'; ?>
</body>
</html>
<?php 
else:
    header( 'Location: ../' );
endif;
?>