<?php if(isset($_SESSION["usuario"])):?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema - Tienda Virtual</title>
    <?php require_once 'inc/header.php'; ?>

      <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <link rel="stylesheet" href="/resources/demos/style.css">

    <script type="text/javascript">
        
    $.datepicker.regional['es'] = {
 closeText: 'Cerrar',
 prevText: '<Ant',
 nextText: 'Sig>',
 currentText: 'Hoy',
 monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
 monthNamesShort: ['Ene','Feb','Mar','Abr', 'May','Jun','Jul','Ago','Sep', 'Oct','Nov','Dic'],
 dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
 dayNamesShort: ['Dom','Lun','Mar','Mié','Juv','Vie','Sáb'],
 dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','Sá'],
 weekHeader: 'Sm',
 dateFormat: 'yy-mm-dd',
 firstDay: 1,
 isRTL: false,
 showMonthAfterYear: false,
 yearSuffix: ''
 };
 $.datepicker.setDefaults($.datepicker.regional['es']);
    $(function () {
        $("#fecha_ini").datepicker();
    });

    $(function () {
        $("#fecha_fin").datepicker();
    });

        
    </script>

</head>
<body>
    <?php require_once 'inc/menu-l.php'; ?>
    <script type="text/javascript">
        $("#reportes").addClass("active");                  
    </script>
    <div class="container-fluid col-md-10 col-md-offset-2">
        <div class="row">
            <div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="space"></div>
                    <div class="navbar navbar-default">
                        <a href="<?php echo BASE_URL; ?>reportes" 
                            class="link-actualizar pull-right"><i class='glyphicon glyphicon-arrow-left'></i> Volver
                        </a>
                    </div>
                    </div>

                    <div class="new-count">
                        <div class="clearfix"></div>
                        <form class="form-horizontal" action="<?php echo BASE_URL; ?>reportes/lista_factura" method="POST" id="form" name="form">
                            <div class="acceso">
                                <input type="hidden" name="guardar" value="1" />
                                <?php if (isset($this->_error)): ?>
                                    <div id="_error" class="alert alert-error">
                                        <a class="close" data-dismiss="alert">x</a>
                                        <?php echo $this->_error; ?>
                                    </div>
                                <?php endif; ?>

                                <?php if (isset($this->_mensaje)): ?>
                                    <div id="_mensaje" class="alert alert-success">
                                        <a class="close" data-dismiss="alert">x</a>
                                        <?php echo $this->_mensaje; ?>
                                    </div>
                                <?php endif; ?>
                                <br>

                                <div class="form-group">
                                    <label for="" class="control-label col-xs-3">Cliente:</label>
                                    <div class="col-xs-8">
                                        <select class="form-control form_imput" name="id_cliente" id="id_cliente" >
                                            <option value="">-Seleccione-</option>
                                            <?php foreach ($this->clientes as $clientes): ?>
                                                    <option value="<?php echo $clientes->id; ?>"><?php echo $clientes->nomcom; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="" class="control-label col-xs-3">Fecha Inicial:</label>
                                    <div class="col-xs-8">
                                        <input type="text" name="fecha_ini" id="fecha_ini" class="datepicker"  >
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="" class="control-label col-xs-3">Fecha Final:</label>
                                    <div class="col-xs-8">
                                        <input type="text" name="fecha_fin" id="fecha_fin" class="datepicker"  >
                                    </div>
                                </div>

                            </div>

                            <center>
                                <input type="submit" class="btn btn-primary btn-center btn" value="buscar">

                            </center>
                        </form>
                    </div>
                </div>
 
</body>
</html>
<?php 
else:
    header( 'Location: ../' );
endif;
?>