<!DOCTYPE html>
<?php
header("Content-Type: application/vnd.ms-excel");
header("Expires: 0");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header("content-disposition: attachment;filename=Reporte.xls");

?>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div id="lista_registros">
                    <?php $total=0;?>     
                        <?php if (isset($this->reporte) && count($this->reporte)) : ?>  
                            <table class="table table-striped table-hover ">
                                <thead>
                                    <tr>
                                        <th class="text-center">N°</th>
                                        <th class="text-center">FECHA</th>
                                        <th class="text-center">PROVEEDOR</th>
                                        <th class="text-center">ESTADO</th>
                                        <th class="text-center">TOTAL</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php foreach($this->reporte as $reporte):?>
                                    <tr>
                                        <td><?php echo $reporte->prefijo." 000".$reporte->num_prefijo;?></td>
                                        <td><?php echo $reporte->fecha_compra;?></td>
                                        <td><?php echo $reporte->razon_social;?></td>
                                        <td class="text-center"><?php if ($reporte->estado_compra == 1){ echo "Creado";} elseif ($reporte->estado_compra == 2){ echo "Finalizado";} ?></td>
                                        <td>$<?php echo $reporte->total_compra;?></td>
                                        <?php $total=$total+$reporte->total_compra; ?>
                                </tr>
                                <?php endforeach;?>
                                <tr>
                                    <td colspan="4">
                                        TOTAL
                                    </td>
                                    <td colspan="1">
                                        $<?php echo $total; ?>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        <?php else: ?>
                        <div class="space"></div>
                        <div class='alert alert-info'>
                        <strong>No hay compras creadas.</strong>
                        </div>
                        <?php endif; ?>
                </div>
            
