<?php if(isset($_SESSION["usuario"])):?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema - Tienda Virtual</title>
    <?php require_once 'inc/header.php'; ?>
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/jquery.fancybox.css" />
    <script src="<?php echo BASE_URL; ?>public/js/jquery.fancybox.js"></script> 
</head>
<body>
    <?php require_once 'inc/menu-l.php'; ?>
    <script type="text/javascript">
        $("#reportes").addClass("active");                  
    </script>
    <div class="container-fluid col-md-10 col-md-offset-2">
        <div class="row">
            <div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="space"></div>
                    <div>
                        <div class="contenido-button">
                            <a href="<?php echo BASE_URL; ?>reportes/exportar_listado_general"><span class="label label-primary">Exportar Excel</span>
                            </a>
                            <a href="<?php echo BASE_URL; ?>reportes/buscar_general"><span class="label label-primary">buscar general</span>
                            </a>
                            <a href="<?php echo BASE_URL; ?>reportes"><span class="label label-primary">Reportes</span>
                            </a>
                        </div>
                    </div>
                </div>

                <form class="form-horizontal" action="#" method="POST" id="form" name="form">
                    <input type="hidden" name="guardar" value="1" />
                    <input type="hidden" name="id_cliente" id="id_cliente" value="<?php echo $_SESSION["id_cliente"]; ?>" />
                    <input type="hidden" name="fecha_ini" id="fecha_ini" value="<?php echo $_SESSION["fecha_ini"]; ?>"/>
                    <input type="hidden" name="fecha_fin" id="fecha_fin" value="<?php echo $_SESSION["fecha_fin"]; ?>" />
                </form>

                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div id="lista_registros">
                    <?php $total=0;?>     
                        <?php if (isset($this->reporte) && count($this->reporte)) : ?>  
                            <table class="table table-striped table-hover ">
                                <thead>
                                    <tr>
                                        <th class="text-center">N° FACTURA</th>
                                        <th class="text-center">N° CERTIFICADO</th>
                                        <th class="text-center">FECHA</th>
                                        <th class="text-center">FORMA PAGO</th>
                                        <th class="text-center">TIPO CLIENTE</th>
                                        <th class="text-center">TIPO DOCUMENTO</th>
                                        <th class="text-center">NUMERO DOCUMENTO</th>
                                        <th class="text-center">CLIENTE</th>
                                        <th class="text-center">PLACA VOLQUETA</th>
                                        <th class="text-center">DEPARTAMENTO</th>
                                        <th class="text-center">CIUDAD</th>
                                        <th class="text-center">VENDEDOR</th>
                                        <th class="text-center">DESPACHADOR</th>
                                        <th class="text-center">ESTADO</th>
                                        <th class="text-center">TOTAL</th>
                                        <th class="text-center">ACCIONES</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php foreach($this->reporte as $reporte):?>
                                    <tr>
                                        <td><?php echo $reporte->prefijo." 000".$reporte->num_prefijo;?></td>
                                        <td><?php echo $reporte->pref_co." 000".$reporte->num_co;?></td>
                                        <td><?php echo $reporte->fecha_venta;?></td>
                                        <td class="text-center"><?php if ($reporte->forma_pago == 1){ echo "Efectivo";} elseif ($reporte->forma_pago == 2){ echo "Remision";} elseif ($reporte->forma_pago == 3){ echo "InfoRem";}?></td>
                                        <td><?php echo $reporte->tipo_cliente;?></td>
                                        <td><?php echo $reporte->tdoc;?></td>
                                        <td><?php echo $reporte->nit;?></td>
                                        <td><?php echo $reporte->nomcom;?></td>
                                        <td><?php echo $reporte->placa;?></td>
                                        <td><?php echo $reporte->departamento;?></td>
                                        <td><?php echo $reporte->ciudad;?></td>
                                        <td><?php echo $reporte->nombres." ".$reporte->apellidos;?></td>
                                        <td><?php echo $reporte->desnom." ".$reporte->desape;?></td>
                                        <td class="text-center"><?php if ($reporte->estado_venta == 1){ echo "Creado";} elseif ($reporte->estado_venta == 2){ echo "Pendiente";} elseif ($reporte->estado_venta == 3){echo "Pendiente Factura";} elseif ($reporte->estado_venta == 4){echo "Finalizado";}?></td>
                                        <td>$<?php echo $reporte->total_venta;?></td>
                                        <?php $total=$total+$reporte->total_venta; ?>
                                        
                                    <td class="text-center">

                                        <a data-toggle="tooltip" data-placement="left" title="Ver documento" target="_blank" href="<?php echo BASE_URL; ?>ventas/ver_documento/<?php echo $reporte->id?>"><span class="glyphicon glyphicon-modal-window"></span></a>
                                        &nbsp;
                                        <!--<a data-toggle="tooltip" data-placement="left" title="Ver certificado" target="_blank" href="<?php echo BASE_URL; ?>ventas/ver_certificado/<?php echo $reporte->id?>"><span class="glyphicon glyphicon-list-alt"></span></a>-->
                                        
                                    </td>
                                </tr>
                                <?php endforeach;?>
                                <tr>
                                    <td colspan="14">
                                        TOTAL
                                    </td>
                                    <td colspan="1">
                                        $<?php echo $total; ?>
                                    </td>
                                    <td colspan="1">

                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="16">
                                        <div class="clear"></div>
                                        <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        <?php else: ?>
                        <div class="space"></div>
                        <div class='alert alert-info'>
                        <strong>No hay ventas creados.</strong>
                        </div>
                        <?php endif; ?>
                </div>
            </div>
        </div>
    </div>  
    <?php require_once 'inc/footer.php'; ?>
    <script type="text/javascript">
        $(function () {
          $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
</body>
</html>
<?php 
else:
    header( 'Location: ../' );
endif;
?>