<!DOCTYPE html>
<html lang="en">
     <head>
     <title>Sistema - Tienda Virtual</title>
     <meta charset="UTF-8">
    <title>Sistema Facturación - Arenera Riopaila</title>
    <?php require_once 'inc/header.php'; ?>
    <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/styles.css">
 
    <script type="text/javascript" src="<?php echo BASE_URL; ?>public/js/jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="<?php echo BASE_URL; ?>public/js/bootstrap.min.js"></script>
     
     <link rel="icon" href="images/favicon.ico">
     <link rel = "shortcut icon" type = "image/png" href = "<?php echo BASE_URL; ?>public/img/favicon.ico" />
     
     <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/style.css">
     <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/EstilosPagina.css" >

     <script src="<?php echo BASE_URL; ?>public/js/jquery.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery_migrate.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/script.js"></script> 
     <script src="<?php echo BASE_URL; ?>public/js/superfish.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.ui.totop.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.equalheights.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.mobilemenu.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.easing.1.3.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/funciones.js"></script>
     
     <!--[if (gt IE 9)|!(IE)]><!-->
     <script src="<?php echo BASE_URL; ?>public/js/jquery.mobile.customized.min.js"></script>
     <!--<![endif]-->

    <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/lightbox.css" />
    <script src="<?php echo BASE_URL; ?>public/js/lightbox-2.6.min.js" type="text/javascript"></script>

<!--*******************************CODIGO DE GOOGLE ANALYTICS NUEVO********************************
   
      <script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
		
		  ga('create', 'UA-64286996-1', 'auto');
		  ga('send', 'pageview');
	 </script>
    
********************************************************************************************-->     
   
    
 </head>
 <body class="main_color">
								    

<!--==============================CONTENIDO=================================--> 
  <div class="main_color">

        <?php include $this->_contenido; ?>
             
  </div>

<!--==============================FOOTER=================================-->

<?php require_once 'inc/footer.php'; ?>

  
        <script type="text/javascript">
            var _ruta_ = '<?php echo BASE_URL; ?>';
        </script>

        <?php if (isset($this->_layoutParams['js_plugin']) && count($this->_layoutParams['js_plugin'])): ?>
            <?php for ($i = 0; $i < count($this->_layoutParams['js_plugin']); $i++): ?>

                <script language="JavaScript" src="<?php echo $this->_layoutParams['js_plugin'][$i] ?>" type="text/javascript"></script>

            <?php endfor; ?>
        <?php endif; ?>


        <?php if (isset($this->_layoutParams['js']) && count($this->_layoutParams['js'])): ?>
            <?php for ($i = 0; $i < count($this->_layoutParams['js']); $i++): ?>

                <script src="<?php echo $this->_layoutParams['js'][$i] ?>" type="text/javascript"></script>

            <?php endfor; ?>
        <?php endif; ?>
          
</body>
</html>