<?php if(isset($_SESSION["usuario"])):?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema - Tienda Virtual</title>
    <?php require_once 'inc/header.php'; ?>
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/jquery.fancybox.css" />
    <script src="<?php echo BASE_URL; ?>public/js/jquery.fancybox.js"></script>
</head>
<body>
    <?php require_once 'inc/menu-l.php'; ?>
    <script type="text/javascript">
        $("#clientes").addClass("active");                  
    </script>
    <div class="container-fluid col-md-10 col-md-offset-2">
        <div class="row">
            <div>
                <div class="space"></div>
                <div class="col-xs-12">
                    <a href="<?php echo BASE_URL; ?>clientes/nuevo_cliente"><span class="label label-primary">Añadir cliente</span></a>
                    <a href="<?php echo BASE_URL; ?>clientes"><span class="label label-primary">Actualizar</span></a>
                </div>
                <div class="space"></div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div id="lista_registros">     
                        <?php if (isset($this->cliente) && count($this->cliente)) : ?>  
                            <table class='table table-striped table-hover'>
                                <thead>
                                    <tr>
                                        <th class="text-center">TIPO CLIENTE</th>
                                        <th class="text-center">TIPO DOCUMENTO</th>
                                        <th class="text-center">NUMERO DOCUMENTO</th>
                                        <th class="text-center">NOMBRE</th>
                                        <th class="text-center">DIRECCION</th>
                                        <th class="text-center">EMAIL</th>
                                        <th class="text-center">TELEFONO</th>
                                        <th class="text-center">ACCIONES</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php foreach($this->cliente as $cliente):?>
                                    <tr class="info">
                                        <td><?php echo $cliente->tipo_cliente;?></td>
                                        <td><?php echo $cliente->tdoc;?></td>
                                        <td><?php echo $cliente->nit;?></td>
                                        <td><?php echo $cliente->nomcom;?></td>
                                        <td><?php echo $cliente->direccion;?></td>
                                        <td><?php echo $cliente->email;?></td>
                                        <td><?php echo $cliente->telefono1;?></td>
                                        <td>
                                            <a href="<?php echo BASE_URL; ?>clientes/editar_cliente/<?php echo $cliente->id?>" class=" ventanacliente"><span class="glyphicon glyphicon-cog"></span></a>

                                            <a href="javascript:borrar_cliente(<?php echo $cliente->id;?>)" class=""><span class="glyphicon glyphicon-trash"></span></a>
                                        </td>
                                </tr>
                                <?php endforeach;?>
                                <tr class="default">
                                    <td colspan="8">
                                        <div class="clear"></div>
                                        <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        <?php else: ?>
                        <div class='alert alert-dismissible alert-danger'>
                            <strong>No hay clientes creados.</strong>
                        </div>
                        <?php endif; ?>
                </div>
            </div>
        </div>
    </div>  
    <?php require_once 'inc/footer.php'; ?>
</body>
</html>
<?php 
else:
    header( 'Location: ../' );
endif;
?>