<?php if(isset($_SESSION["usuario"])):?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema - Tienda Virtual</title>
    <?php require_once 'inc/header.php'; ?>
</head>
<body>
    <?php require_once 'inc/menu-l.php'; ?>
    <script type="text/javascript">
        $("#clientes").addClass("active");                  
    </script>
    <div class="container-fluid col-md-10 col-md-offset-2">
        <div class="row">
            <div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="space"></div>
                    <div class="navbar navbar-default">
                            <a href="<?php echo BASE_URL; ?>clientes" 
                                class="link-actualizar pull-right"><i class='glyphicon glyphicon-arrow-left'></i> Volver
                            </a>
                        </div>
                    </div>

                    <div class="new-count">
                        <div class="clearfix"></div>
                        <form class="form-horizontal" action="" method="POST" id="form" name="form1">
                            <div class="acceso">
                                <input type="hidden" name="guardar" value="1" />
                                <?php if (isset($this->_error)): ?>
                                    <div id="_error" class="alert alert-error">
                                        <a class="close" data-dismiss="alert">x</a>
                                        <?php echo $this->_error; ?>
                                    </div>
                                <?php endif; ?>

                                <?php if (isset($this->_mensaje)): ?>
                                    <div id="_mensaje" class="alert alert-success">
                                        <a class="close" data-dismiss="alert">x</a>
                                        <?php echo $this->_mensaje; ?>
                                    </div>
                                <?php endif; ?>
                                <br>

                                <div class="form-group">
                                    <label for="" class="control-label col-xs-3">Tipo Empresa:</label>
                                    <div class="col-xs-8">
                                        <select class="form-control form_imput" name="tipo_empresa" id="tipo_empresa" >
                                            <option value="">-Seleccione-</option>
                                            <?php foreach ($this->empresa as $empresa): ?>
                                                    <option value="<?php echo $empresa->id; ?>"><?php echo $empresa->tipo_cliente; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="" class="control-label col-xs-3">Tipo Documento:</label>
                                    <div class="col-xs-8">
                                        <select class="form-control form_imput" name="tipo_doc" id="tipo_doc" >
                                            <option value="">-Seleccione-</option>
                                            <?php foreach ($this->documento as $documento): ?>
                                                    <option value="<?php echo $documento->id; ?>"><?php echo $documento->tipo_documento; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group label-floating">
                                    <label for="" class="control-label col-xs-3">Numero Documento:</label>
                                    <div class="col-xs-8">
                                        <input type="text" name="numdoc" id="numdoc" class="form-control" required placeholder="Numero Documento" value="">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="" class="control-label col-xs-3">Rucom:</label>
                                    <div class="col-xs-8">
                                        <input type="text" name="rucom" id="rucom" class="form-control" required
                                            placeholder="RUCOM" value="">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="" class="control-label col-xs-3">Razon Social:</label>
                                    <div class="col-xs-8">
                                        <input type="text" name="rsocial" id="rsocial" class="form-control" required
                                            placeholder="Razon Social" value="">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="" class="control-label col-xs-3">Nombre Comercial:</label>
                                    <div class="col-xs-8">
                                        <input type="text" name="nomcom" id="nomcom" class="form-control" required placeholder="Nombre Comercial" value="">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="" class="control-label col-xs-3">Telefono1:</label>
                                    <div class="col-xs-8">
                                        <input type="text" name="tel1" id="tel1" class="form-control" required placeholder="Telefono 1" value="">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="" class="control-label col-xs-3">Telefono2:</label>
                                    <div class="col-xs-8">
                                        <input type="text" name="tel2" id="tel2" class="form-control" 
                                            placeholder="Telefono 2" value="">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="" class="control-label col-xs-3">Direccion:</label>
                                    <div class="col-xs-8">
                                        <input type="text" name="dir" id="dir" class="form-control" required placeholder="Direccion" value="">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="" class="control-label col-xs-3">Email:</label>
                                    <div class="col-xs-8">
                                        <input type="text" name="email" id="email" class="form-control" required placeholder="Email" value="">
                                    </div>
                                </div>

                            </div>

                            <center>
                                <a href="#" class="btn btn-primary btn-center btn" onclick="document.getElementById('form').submit()">Guardar</a>
                            </center>
                        </form>
                    </div>
                </div>
 
</body>
</html>
<?php 
else:
    header( 'Location: ../' );
endif;
?>