<?php if (isset($this->cliente) && count($this->cliente)) : ?>  
                            <table class='table  table-bordered table-hover table-condensed'>
                                <thead class="alert alert-info text-head">
                                    <tr>
                                        <th class="text-center">TIPO CLIENTE</th>
                                        <th class="text-center">TIPO DOCUMENTO</th>
                                        <th class="text-center">NUMERO DOCUMENTO</th>
                                        <th class="text-center">NOMBRE</th>
                                        <th class="text-center">DIRECCION</th>
                                        <th class="text-center">EMAIL</th>
                                        <th class="text-center">TELEFONO</th>
                                        <th class="text-center">ACCIONES</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php foreach($this->cliente as $cliente):?>
                                    <tr>
                                        <td><?php echo $cliente->tipo_cliente;?></td>
                                        <td><?php echo $cliente->tdoc;?></td>
                                        <td><?php echo $cliente->nit;?></td>
                                        <td><?php echo $cliente->nomcom;?></td>
                                        <td><?php echo $cliente->direccion;?></td>
                                        <td><?php echo $cliente->email;?></td>
                                        <td><?php echo $cliente->telefono1;?></td>
                                    <td>
                                        <a href="<?php echo BASE_URL; ?>clientes/editar_cliente/<?php echo $cliente->id?>" class="btn2 ventanacliente"><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/> </a>

                                        <a href="javascript:borrar_cliente(<?php echo $cliente->id;?>)" class="btn2"><img src="<?php echo BASE_URL; ?>public/img/remover_todos.png" style="vertical-align:middle"/></a>
                                    </td>
                                </tr>
                                <?php endforeach;?>
                                <tr>
                                    <td colspan="8">
                                        <div class="clear"></div>
                                        <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        <?php else: ?>
                        <div class='alert alert-info'>
                        <strong>No hay clientes creados.</strong>
                        </div>
                        <?php endif; ?>