<!DOCTYPE html>
<html lang="en">
     <head>
     <title><?php if (isset($this->titulo)) echo $this->titulo; ?></title>
     <meta charset="utf-8">
     <meta name = "format-detection" content = "telephone=no" />
     <link rel="icon" href="images/favicon.ico">
     <link rel = "shortcut icon" type = "image/png" href = "<?php echo BASE_URL; ?>public/img/favicon.ico" />
     
     <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/style.css">
     <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/EstilosPagina.css" >
     <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/custom-theme/jquery-ui-1.10.3.custom.css">
        
     <script src="<?php echo BASE_URL; ?>public/js/jquery.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery_migrate.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/script.js"></script> 
     <script src="<?php echo BASE_URL; ?>public/js/superfish.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.ui.totop.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.equalheights.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.mobilemenu.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.easing.1.3.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
	 <script src="<?php echo BASE_URL; ?>public/js/CalendarioEspanol.js" type="text/javascript"></script>
     
     <!--[if (gt IE 9)|!(IE)]><!-->
     <script src="<?php echo BASE_URL; ?>public/js/jquery.mobile.customized.min.js"></script>
     <!--<![endif]-->


    <!--[if lt IE 8]>
       <div style=' clear: both; text-align:center; position: relative;'>
         <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
           <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
         </a>
      </div>
      <![endif]-->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <link rel="stylesheet" media="screen" href="css/ie.css">


    <![endif]-->

    

<style type="text/css">
            .titulo1{
            font-size:20px;
            color:#a0a2a2;
            font-weight:900;
            }

            .titulo2{
            font-size:14px;
            color:#a0a2a2;
            font-weight:900;
            }

            .form_imput{
            width:240px;
            height:32px;
            border:1px solid #cdcfd2;
            }

            .form_imput::-moz-placeholder{
            color:#777;opacity:
            }

            .form_imput:focus{
            border-color:#0B6EC7;
            -webkit-box-shadow:inset 0 1px 1px rgba(0,0,0,0.075),0 0 6px #0B6EC7;
            box-shadow:inset 0 1px 1px rgba(0,0,0,0.075),0 0 6px #0B6EC7
            }
            
        </style>

     </head>
     
<body class="main_color" align="center">
    <span class="titulo1">INFORMACIÓN CLIENTE</span><br><br>
    <table cellpadding="3" cellspacing="0" width="80%" border="0" style="margin-left:10%;">
        <tr>
            <td><span class="titulo2">NOMBRE: </span></td>
            <td><span class="titulo2"><?php if (isset($this->cliente->nombre)) echo $this->cliente->nombre; ?></span></td>
        </tr>
        <tr>
            <td><span class="titulo2">TIPO DE DOCUMENTO: </span></td>
            <td><span class="titulo2"><?php if (isset($this->cliente->tipo_doc)) echo $this->cliente->tipo_doc; ?></span></td>
        </tr>
        <tr>
            <td><span class="titulo2">NUM. DOCUMENTO: </span></td>
            <td><span class="titulo2"><?php if (isset($this->cliente->num_doc)) echo $this->cliente->num_doc; ?></span></td>
        </tr>
        <tr>
            <td><span class="titulo2">FECHA REGISTRO: </span></td>
            <td><span class="titulo2"><?php if (isset($this->cliente->fecha_reg)) echo $this->cliente->fecha_reg; ?></span></td>
        </tr>
        <tr>
            <td><span class="titulo2">FECHA NACIMIENTO: </span></td>
            <td><span class="titulo2"><?php if (isset($this->cliente->fecha_nac)) echo $this->cliente->fecha_nac; ?></span></td>
        </tr>
        <tr>
            <td><span class="titulo2">TEL&Eacute;FONO: </span></td>
            <td><span class="titulo2"><?php if (isset($this->cliente->telefono)) echo $this->cliente->telefono; ?></span></td>
        </tr>
        <tr>
            <td><span class="titulo2">CELULAR: </span></td>
            <td><span class="titulo2"><?php if (isset($this->cliente->celular)) echo $this->cliente->celular; ?></span></td>
        </tr>
        <tr>
            <td><span class="titulo2">DIRECCI&Oacute;N: </span></td>
            <td><span class="titulo2"><?php if (isset($this->cliente->direccion)) echo $this->cliente->direccion; ?></span></td>
        </tr>
        <tr>
            <td><span class="titulo2">EMAIL: </span></td>
            <td><span class="titulo2"><?php if (isset($this->cliente->email)) echo $this->cliente->email; ?></span></td>
        </tr>
        <tr>
            <td><span class="titulo2">USUARIO: </span></td>
            <td><span class="titulo2"><?php if (isset($this->cliente->usuario)) echo $this->cliente->usuario; ?></span></td>
        </tr>
    </table>
 </body>