<?php if(isset($_SESSION["usuario"])):?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema - Tienda Virtual</title>
    <?php require_once 'inc/header.php'; ?>
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/jquery.fancybox.css" />
    <script src="<?php echo BASE_URL; ?>public/js/jquery.fancybox.js"></script>
</head>
<body>
    <?php require_once 'inc/menu-l.php'; ?>
    <script type="text/javascript">
        $("#empleados").addClass("active");                  
    </script>
    <div class="container-fluid col-md-10 col-md-offset-2">
        <div class="row">
            <div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="space"></div>
                    <div>
                        <div class="contenido-button">
                            <a href="<?php echo BASE_URL; ?>empleados/nuevo_empleado"><span class="label label-primary">Nuevo empleado</span></a>

                            <a href="<?php echo BASE_URL; ?>empleados"><span class="label label-primary">Actualizar</span>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div id="lista_registros">     
                        <?php if (isset($this->empleado) && count($this->empleado)) : ?>  
                            <table class="table table-striped table-hover ">
                                <thead>
                                    <tr>
                                        <th class="text-center">CODIGO EMPLEADO</th>
                                        <th class="text-center">TIPO DOCUMENTO</th>
                                        <th class="text-center">NUMERO DOCUMENTO</th>
                                        <th class="text-center">NOMBRE</th>
                                        <th class="text-center">SALARIO</th>
                                        <th class="text-center">ACCIONES</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php foreach($this->empleado as $empleado):?>
                                    <tr>
                                        <td><?php echo $empleado->codigo;?></td>
                                        <td><?php echo $empleado->tdoc;?></td>
                                        <td><?php echo $empleado->documento;?></td>
                                        <td><?php echo $empleado->nombres." ".$empleado->apellidos;?></td>
                                        <td>$<?php echo $empleado->salario_b;?></td>
                                    <td>
                                        <a href="<?php echo BASE_URL; ?>empleados/editar_empleado/<?php echo $empleado->id?>" class="ventanaempleados"><span class="label label-primary">Editar</span></a>

                                        <a href="javascript:borrar_empleado(<?php echo $empleado->id;?>)"><span class="label label-primary">Borrar</span></a>
                                    </td>
                                </tr>
                                <?php endforeach;?>
                                <tr>
                                    <td colspan="6">
                                        <div class="clear"></div>
                                        <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        <?php else: ?>
                        <div class='alert alert-info'>
                        <strong>No hay empleados creados.</strong>
                        <p><a href="<?php echo BASE_URL; ?>empleados/nuevo_empleado"><span class="label label-primary text-center">Añadir un nuevo empleado</span></a></p>
                        </div>
                        <?php endif; ?>
                </div>
            </div>
        </div>
    </div>  
    <?php require_once 'inc/footer.php'; ?>
</body>
</html>
<?php 
else:
    header( 'Location: ../' );
endif;
?>