<?php if(isset($_SESSION["usuario"])):?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema - Tienda Virtual</title>
    <?php require_once 'inc/header.php'; ?>
</head>
<body>
    <?php require_once 'inc/menu-l.php'; ?>
    <script type="text/javascript">
        $("#empleados").addClass("active");                  
    </script>
    <div class="container-fluid col-md-10 col-md-offset-2">
        <div class="row">
            <div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="space"></div>
                    <div class="navbar navbar-default">
                            <a href="<?php echo BASE_URL; ?>empleados" 
                                class="link-actualizar pull-right"><i class='glyphicon glyphicon-arrow-left'></i> Volver
                            </a>
                        </div>
                    </div>

                    <div class="new-count">
                        <div class="clearfix"></div>
                        <form class="form-horizontal" action="" method="POST" id="form" name="form1">
                            <div class="acceso">
                                <input type="hidden" name="guardar" value="1" />
                                <?php if (isset($this->_error)): ?>
                                    <div id="_error" class="alert alert-error">
                                        <a class="close" data-dismiss="alert">x</a>
                                        <?php echo $this->_error; ?>
                                    </div>
                                <?php endif; ?>

                                <?php if (isset($this->_mensaje)): ?>
                                    <div id="_mensaje" class="alert alert-success">
                                        <a class="close" data-dismiss="alert">x</a>
                                        <?php echo $this->_mensaje; ?>
                                    </div>
                                <?php endif; ?>
                                <br>

                                <div class="form-group">
                                    <label for="" class="control-label col-xs-3">Codigo Empleado:</label>
                                    <div class="col-xs-8">
                                        <input type="text" name="codigo" id="codigo" class="form-control" required placeholder="codigo" value="">
                                    </div>
                                </div> 

                                <div class="form-group">
                                    <label for="" class="control-label col-xs-3">Tipo Documento:</label>
                                    <div class="col-xs-8">
                                        <select class="form-control form_imput" name="tipo_doc" id="tipo_doc" >
                                            <option value="">-Seleccione-</option>
                                            <?php foreach ($this->documento as $documento): ?>
                                                    <option value="<?php echo $documento->id; ?>"><?php echo $documento->tipo_documento; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="" class="control-label col-xs-3">Numero Documento:</label>
                                    <div class="col-xs-8">
                                        <input type="text" name="numdoc" id="numdoc" class="form-control" required placeholder="Numero Documento" value="">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="" class="control-label col-xs-3">Nombres:</label>
                                    <div class="col-xs-8">
                                        <input type="text" name="nombres" id="nombres" class="form-control" required
                                            placeholder="Nombres" value="">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="" class="control-label col-xs-3">Apellidos:</label>
                                    <div class="col-xs-8">
                                        <input type="text" name="apellidos" id="apellidos" class="form-control" required
                                            placeholder="Apellidos" value="">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="" class="control-label col-xs-3">Salario:</label>
                                    <div class="col-xs-8">
                                        <input type="text" name="salario" id="salario" class="form-control" required placeholder="Salario" value="">
                                    </div>
                                </div>

                            </div>

                            <center>
                                <a href="#" class="btn btn-primary btn-center btn" onclick="document.getElementById('form').submit()">Guardar</a>
                            </center>
                        </form>
                    </div>
                </div>
 
</body>
</html>
<?php 
else:
    header( 'Location: ../' );
endif;
?>