<?php if (isset($this->empleado) && count($this->empleado)) : ?>  
                            <table class="table table-striped table-hover ">
                                <thead>
                                    <tr>
                                        <th class="text-center">CODIGO EMPLEADO</th>
                                        <th class="text-center">TIPO DOCUMENTO</th>
                                        <th class="text-center">NUMERO DOCUMENTO</th>
                                        <th class="text-center">NOMBRE</th>
                                        <th class="text-center">SALARIO</th>
                                        <th class="text-center">ACCIONES</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php foreach($this->empleado as $empleado):?>
                                    <tr>
                                        <td><?php echo $empleado->codigo;?></td>
                                        <td><?php echo $empleado->tdoc;?></td>
                                        <td><?php echo $empleado->documento;?></td>
                                        <td><?php echo $empleado->nombres." ".$empleado->apellidos;?></td>
                                        <td>$<?php echo $empleado->salario_b;?></td>
                                    <td>
                                        <a href="<?php echo BASE_URL; ?>empleados/editar_empleado/<?php echo $empleado->id?>" class="ventanaempleados"><span class="label label-primary">Editar</span></a>

                                        <a href="javascript:borrar_empleado(<?php echo $empleado->id;?>)"><span class="label label-primary">Borrar</span></a>
                                    </td>
                                </tr>
                                <?php endforeach;?>
                                <tr>
                                    <td colspan="6">
                                        <div class="clear"></div>
                                        <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        <?php else: ?>
                        <div class='alert alert-info'>
                        <strong>No hay empleados creados.</strong>
                        <p><a href="<?php echo BASE_URL; ?>empleados/nuevo_empleado"><span class="label label-primary text-center">Añadir un nuevo empleado</span></a></p>
                        </div>
                        <?php endif; ?>